#Common_elements
txt_userName="name:user-name"
txt_password="name:password"
txt_login_button="name:login-button"
txt_highprice="(//div[@class='inventory_item_price'])[1]"
txt_lowprice="(//div[@class='inventory_item_price'])[6]"
txt_FirstName="id:first-name"
txt_LastName="id:last-name"
txt_ZipCode="id:postal-code"